import {useState,useMemo,useRef,useEffect} from 'react';
import {ArrowUpRight,ArrowRight,Compass,BookOpen,MessageCircle,Sun,Moon,Settings2,Volume2,VolumeX,Plus,Minus,LocateFixed,RotateCcw,ChevronRight,ChevronLeft,Search,Bookmark,MapPin,Users,Send,Sparkles,Leaf,Footprints,Check,Trash2,SlidersHorizontal,ExternalLink,PanelRightClose,PanelRightOpen,X} from 'lucide-react';
import World from './world/World.jsx';
import {WorldEngine} from './world/engine.js';
import {PLACES,AGENTS,THEMES} from './world/config.js';
import editions from './data/editions.json';
import {readStore,writeStore,memoryFor} from './storage.js';
import Dialog from './Dialog.jsx';
const allWorks=editions.flatMap(e=>e.works);
const initialEvents=[{id:'welcome',text:'山门已开，欢迎来到原子江湖',kind:'welcome',time:Date.now()}];
function useSaved(key,fallback){const [v,set]=useState(()=>readStore(key,fallback));const update=n=>set(prev=>{const next=typeof n==='function'?n(prev):n;writeStore(key,next);return next;});return [v,update];}
const Avatar=({agent,size=36})=><span className="avatar" style={{'--avatar-color':agent?.color||'#427ab5',width:size,height:size}}><span className="avatar-hat"/><span className="avatar-eyes">••</span></span>;
export default function App(){
 const [events,setEvents]=useState(initialEvents),engine=useMemo(()=>new WorldEngine(e=>setEvents(p=>[e,...p].slice(0,12))),[]),[agents,setAgents]=useState(()=>engine.snapshot());
 const [theme,setTheme]=useSaved('theme','jianghu'),[night,setNight]=useSaved('night',false),[nickname,setNickname]=useSaved('nickname','初来江湖的你'),[playerColor,setPlayerColor]=useSaved('color','#427ab5');
 const [bookmarks,setBookmarks]=useSaved('bookmarks',[]),[memories,setMemories]=useSaved('memories',[]),[remember,setRemember]=useSaved('remember',false),[visits,setVisits]=useSaved('visits',[]);
 const [panel,setPanel]=useState(null),[location,setLocation]=useState('town'),[placeId,setPlaceId]=useState(null),[chatId,setChatId]=useState(null),[editionId,setEditionId]=useState('funskills'),[track,setTrack]=useState('全部'),[search,setSearch]=useState(''),[workId,setWorkId]=useState(null),[journalTab,setJournalTab]=useState('收藏作品'),[toast,setToast]=useState(''),[showLabels,setShowLabels]=useState(true),[rail,setRail]=useState(true),[mode,setMode]=useState('demo'),[draft,setDraft]=useState(''),[messages,setMessages]=useState({}),[sending,setSending]=useState(false);
 useEffect(()=>{engine.player.name=nickname==='初来江湖的你'?'你':nickname||'你';},[nickname,engine]);
 const apiRef=useRef(),abortRef=useRef(),chatScroll=useRef(),toastTimer=useRef(),memoryRev=useRef(0);
 const currentEdition=editions.find(e=>e.id===editionId)||editions[0],work=allWorks.find(w=>w.id===workId),place=PLACES.find(p=>p.id===placeId),chatAgent=AGENTS.find(a=>a.id===chatId);
 const filtered=useMemo(()=>currentEdition.works.filter(w=>(track==='全部'||w.track===track)&&(!search||`${w.title}${w.author}${w.description}${w.tags.join('')}`.toLowerCase().includes(search.toLowerCase()))),[currentEdition,track,search]);
 const sceneWorks=useMemo(()=>filtered.slice(0,8),[filtered]);
 function notice(text){setToast(text);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),3500);}
 useEffect(()=>{fetch('/api/status').then(r=>r.ok?r.json():null).then(d=>{if(d)setMode(d.mode);}).catch(()=>{});const id=new URLSearchParams(window.location.search).get('work');const w=allWorks.find(w=>w.id===id);if(w){setEditionId(w.editionId);setLocation('hall');setPanel('gallery');setWorkId(id);}return()=>{clearTimeout(toastTimer.current);abortRef.current?.abort();};},[]);
 useEffect(()=>{if(chatScroll.current)chatScroll.current.scrollTop=chatScroll.current.scrollHeight;},[messages,sending]);
 useEffect(()=>{function nav(){const id=new URLSearchParams(window.location.search).get('work');setWorkId(allWorks.some(w=>w.id===id)?id:null);}window.addEventListener('popstate',nav);return()=>window.removeEventListener('popstate',nav);},[]);
 function closeChat(){abortRef.current?.abort();setSending(false);if(chatId)engine.release(chatId);setChatId(null);setPanel(null);setDraft('');}
 function closePanel(){if(panel==='chat')closeChat();else setPanel(null);}
 function openPanel(id){if(chatId)closeChat();setPanel(id);}
 function enterHall(){if(chatId)closeChat();setLocation('hall');setPanel('gallery');setPlaceId(null);notice('已进入武林大会展示馆');}
 function openWork(id){const w=allWorks.find(w=>w.id===id);if(!w)return;setWorkId(id);const url=new URL(window.location.href);url.searchParams.set('work',id);history.pushState({},'',url);setVisits(v=>[{id,time:Date.now()},...v.filter(x=>x.id!==id)].slice(0,50));}
 function closeWork(){setWorkId(null);const url=new URL(window.location.href);url.searchParams.delete('work');history.replaceState({},'',url);}
 function toggleBookmark(id){setBookmarks(v=>v.includes(id)?v.filter(x=>x!==id):[id,...v]);}
 function startChat(id){if(chatId)closeChat();engine.hold(id);setChatId(id);setPanel('chat');setMessages(v=>({...v,[id]:v[id]||[{role:'assistant',content:AGENTS.find(a=>a.id===id).line}]}));setDraft('');}
 function openPlace(id){setPlaceId(id);openPanel('place');}
 async function sendMessage(text=draft){text=text.trim();if(!text||sending||!chatId)return;const id=chatId,rev=memoryRev.current;const historyMessages=messages[id]||[];setDraft('');setSending(true);setMessages(v=>({...v,[id]:[...(v[id]||[]),{role:'user',content:text}]}));const controller=new AbortController();abortRef.current=controller;
  try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,agentId:id,history:historyMessages,memories:remember?memoryFor(memories,id):[]}),signal:controller.signal});const d=await r.json();if(!r.ok)throw new Error(d.error||'暂时无法回复');if(controller.signal.aborted||rev!==memoryRev.current)return;setMode(d.mode);setMessages(v=>({...v,[id]:[...(v[id]||[]),{role:'assistant',content:d.text,workIds:d.workIds}]}));
   if(remember&&/我.*(喜欢|感兴趣|想学|在做)|记住/.test(text)){setMemories(v=>[...v,{id:crypto.randomUUID(),agentId:id,text,time:Date.now(),source:'你主动表达的兴趣'}].slice(-60));}
  }catch(e){if(e.name!=='AbortError')setMessages(v=>({...v,[id]:[...(v[id]||[]),{role:'assistant',content:e.message,error:true}]}));}finally{if(abortRef.current===controller)setSending(false);}
 }
 function deleteMemory(id){memoryRev.current++;abortRef.current?.abort();setSending(false);setMemories(m=>id?m.filter(x=>x.id!==id):[]);setMessages({});notice(id?'记忆已删除，相关对话上下文已清除':'所有私人记忆与对话上下文已清除');}
 function changeRemember(value){memoryRev.current++;abortRef.current?.abort();setSending(false);setRemember(value);setMessages({});}
 async function share(){try{await navigator.clipboard.writeText(window.location.href);notice('作品链接已复制');}catch{notice('可复制地址栏中的作品链接');}}
 function workCard(w){return <button className="work-card" key={w.id} onClick={()=>openWork(w.id)}><div className="work-image"><img src={w.thumb} alt={w.title} loading="lazy"/><span>{w.track}</span>{bookmarks.includes(w.id)&&<Bookmark size={17} fill="currentColor"/>}</div><div className="work-copy"><h3>{w.title}</h3><p>{w.tagline}</p><footer><span>{w.author}</span><ArrowUpRight size={16}/></footer></div></button>;}
 return <div className={`app ${night?'night':''}`}>
  <header className="topbar">
   <button className="brand" onClick={()=>{closePanel();setLocation('town');apiRef.current?.reset();}} aria-label="回到原子江湖"><span className="brand-seal">原<span>子</span></span><span className="brand-word">原子江湖<small>ATOMHUB · A LIVING WORLD</small></span></button>
   <nav aria-label="主导航"><button className={location==='town'&&!['journal','about'].includes(panel)?'active':''} onClick={()=>{closePanel();setLocation('town');}}><Compass size={17}/>漫游小镇</button><button className={location==='hall'?'active':''} onClick={enterHall}><BookOpen size={17}/>武林大会</button><button className={panel==='journal'?'active':''} onClick={()=>openPanel('journal')}><Bookmark size={16}/>游历手札{bookmarks.length>0&&<b>{bookmarks.length}</b>}</button></nav>
   <div className="top-actions"><span className="world-status"><i/>本地世界</span><button className="profile-button" onClick={()=>openPanel('settings')} aria-label="定制我的侠客"><Avatar size={34}/><span>{nickname==='初来江湖的你'?'少侠':nickname}</span><ChevronRight size={14}/></button></div>
  </header>
  <main className={`world-layout ${rail?'':'rail-hidden'}`}>
   <div className="world-stage">
    <World engine={engine} theme={theme} night={night} location={location} works={sceneWorks} onPlace={openPlace} onAgent={startChat} onWork={openWork} onSnapshot={setAgents} apiRef={apiRef} playerColor={playerColor} labels={showLabels}/>
    <div className="scene-intro"><span className="eyebrow"><span className="tiny-star">✳</span> 人与 AGENT 共建的开源学习社区</span><h1>{location==='town'?'山水有相逢，江湖有同路。':'让每一个好想法，被看见。'}</h1><p>{location==='town'?'在这里歇歇脚，聊聊想法，和有趣的灵魂一起创造。':'走近展台，发现来自真实赛事的作品与创作者。'}</p></div>
    <div className="scene-weather">{night?<Moon size={17}/>:<Sun size={18}/>}<span>{night?'月上枝头':'日光正好'}<small>{night?'灯火可亲 · 夜景':'草木葱茏 · 日景'}</small></span></div>
    {location==='hall'&&<button className="back-to-town" onClick={()=>{setLocation('town');closePanel();}}><ChevronLeft size={16}/>返回小镇</button>}
    <div className="map-caption"><div className="compass-mark"><span>N</span><Compass size={37} strokeWidth={1}/></div><div><span className="eyebrow">{location==='town'?'THE ATOM VILLAGE':'THE EXHIBITION HALL'}</span><h2>{location==='town'?'原子公社 · 江湖初见':'武林大会 · 灵感长廊'}</h2><p><MapPin size={13}/>{location==='town'?'原子广场':'比赛展示馆'}<span>·</span>{location==='town'?'8 位 AI 侠客在此生活':`${filtered.length} 份作品可供探索`}</p></div></div>
    <div className="world-tools"><button aria-label="放大地图" onClick={()=>apiRef.current?.zoom(.85)}><Plus size={18}/></button><button aria-label="缩小地图" onClick={()=>apiRef.current?.zoom(1.15)}><Minus size={18}/></button><span/><button aria-label="回到我的角色" onClick={()=>apiRef.current?.locate()}><LocateFixed size={18}/></button><button aria-label="重置视角" onClick={()=>apiRef.current?.reset()}><RotateCcw size={17}/></button><span/><button aria-label={night?'切换日景':'切换夜景'} onClick={()=>setNight(v=>!v)}>{night?<Sun size={18}/>:<Moon size={18}/>}</button><button aria-label="小镇设置" onClick={()=>openPanel('settings')}><Settings2 size={18}/></button></div>
    <div className="controls-tip"><span className="mouse-icon"/>点击地面行走<span>·</span>拖动旋转<span>·</span>滚轮缩放</div>
   </div>
   <button className="rail-toggle icon-button" aria-label={rail?'收起侧栏':'展开侧栏'} onClick={()=>setRail(v=>!v)}>{rail?<PanelRightClose size={18}/>:<PanelRightOpen size={18}/>}</button>
   {rail&&<aside className="right-rail">
    <section className="welcome-card"><span className="eyebrow">初入江湖 · 幸会少侠</span><h2>相逢即是<br/>江湖同路人<span>。</span></h2><div className="hero-art"><img src="/brand/hero-ip.webp" alt="原子公社白蓝斗笠侠客 IP"/><span className="ip-note">原子公社 · 原创 IP</span></div><p>我是阿原，你的点灯人。<br/>一盏茶的工夫，认识这片新江湖。</p><button className="primary-button" onClick={()=>startChat('ayuan')}><MessageCircle size={17}/>和阿原聊聊<ArrowUpRight size={17}/></button><button className="text-button" onClick={()=>openPanel('about')}>先了解原子公社<ArrowRight size={15}/></button></section>
    <section className="rail-section happenings"><header><h3><span className="green-dot"/>江湖此刻</h3><span>模拟动态</span></header><div className="event-list">{events.slice(0,3).map((e,i)=><div className="event" key={e.id}><span className={`event-icon ${e.kind}`}>{e.kind==='chat'?<MessageCircle size={13}/>:e.kind==='welcome'?<Leaf size={13}/>:<Footprints size={13}/>}</span><div><p>{e.text}</p><small>{i===0?'刚刚':'片刻前'}</small></div></div>)}</div></section>
    <section className="rail-section nearby"><header><h3>遇见同行侠客</h3><button onClick={()=>openPanel('people')} aria-label="查看所有侠客">全部 <ArrowRight size={13}/></button></header><div className="nearby-avatars">{AGENTS.slice(0,5).map(a=><button key={a.id} title={`${a.name} · ${agents.find(x=>x.id===a.id)?.state}`} onClick={()=>startChat(a.id)}><Avatar agent={a} size={38}/><small>{a.name}</small></button>)}</div><p><i/>8 位 AI 伙伴 · 随时可以打个招呼</p></section>
    <button className="exhibition-promo" onClick={enterHall}><span className="promo-icon"><BookOpen size={22}/></span><span><small>灵感在这里相遇</small><strong>去武林大会逛逛</strong></span><ArrowUpRight size={20}/></button>
    <footer className="rail-footer">每个人都是一颗原子，聚在一起便是江湖。<button onClick={()=>openPanel('about')}>关于这个世界 ↗</button></footer>
   </aside>}
  </main>
  {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}
  {panel==='gallery'&&<Dialog title="武林大会展示馆" subtitle="EXHIBITIONS · 真实作品，长久相逢" onClose={closePanel} className="gallery-dialog" hidden={!!work}><div className="edition-tabs">{editions.map(e=><button key={e.id} className={e.id===editionId?'active':''} onClick={()=>{setEditionId(e.id);setTrack('全部');setSearch('');}}>{e.title}<span>{e.works.length} 份作品</span></button>)}</div><div className="edition-intro"><span className="eyebrow">{currentEdition.subtitle}</span><p>{currentEdition.description}</p></div><div className="gallery-tools"><div className="search-field"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索作品、作者或灵感…" aria-label="搜索作品"/>{search&&<button onClick={()=>setSearch('')} aria-label="清空搜索"><X size={15}/></button>}</div><select value={track} onChange={e=>setTrack(e.target.value)} aria-label="筛选赛道"><option>全部</option>{currentEdition.tracks.map(t=><option key={t}>{t}</option>)}</select></div><div className="result-line"><span>{filtered.length} 份作品</span><span>展厅展示前 8 件 · 完整内容见下方</span></div><div className="work-grid">{filtered.map(workCard)}{filtered.length===0&&<div className="empty-state"><Search/><h3>暂未找到相关作品</h3><p>试试其他关键词或切换赛道。</p><button className="secondary-button" onClick={()=>{setSearch('');setTrack('全部');}}>清除筛选</button></div>}</div><p className="source-note">{currentEdition.note}</p><button className="secondary-button gallery-walk" onClick={closePanel}><Footprints size={16}/>收起目录，看看 3D 展厅</button></Dialog>}
  {work&&<Dialog title={work.title} subtitle={`${editions.find(e=>e.id===work.editionId).title} / ${work.track}`} onClose={closeWork} className="work-dialog"><div className="work-detail"><a href={work.poster} target="_blank" rel="noreferrer" className="poster-link"><img src={work.poster} alt={`${work.title}原始作品海报`}/><span><ExternalLink size={14}/>打开原图</span></a><div className="work-description"><div className="author-line"><Avatar size={32}/><div><small>作品作者</small><p>{work.author}</p></div></div><blockquote>{work.tagline}</blockquote><h3>关于这个作品</h3><p>{work.description}</p><div className="tag-list">{work.tags.map(t=><span key={t}>{t}</span>)}</div><div className="detail-actions"><button className="primary-button" onClick={()=>toggleBookmark(work.id)}><Bookmark size={17} fill={bookmarks.includes(work.id)?'currentColor':'none'}/>{bookmarks.includes(work.id)?'已收入手札':'收藏到手札'}</button><button className="secondary-button" onClick={share}><ArrowUpRight size={17}/>分享作品</button></div><p className="source-note">来源：原赛事展示资料。作品效果与成果为作者资料陈述。收藏保存在此浏览器。</p></div></div></Dialog>}
  {panel==='place'&&place&&<Dialog title={place.name} subtitle="江湖地图 · 一处相逢" onClose={closePanel} className="small-dialog"><div className="place-detail"><div className={`place-illustration ${place.id}`}><span>{place.id==='hall'?'展':place.id==='tea'?'茶':place.id==='library'?'书':place.id==='workshop'?'创':place.id==='future-lodge'?'待':'星'}</span></div>{place.status==='placeholder'&&<span className="placeholder-badge">占位建筑 · 等待功能定义</span>}<h3>{place.subtitle}</h3><p>{place.description}</p><div className="detail-actions">{place.status==='placeholder'?<button className="secondary-button" onClick={()=>{setPanel(null);apiRef.current?.focus(place.id);notice('正在前往这座待定建筑');}}><Footprints size={16}/>去看看占位空间</button>:<button className="primary-button" onClick={()=>{if(place.id==='hall')enterHall();else if(place.id==='tea')startChat('qinghe');else if(place.id==='workshop')startChat('xingzhou');else openPanel('about');}}>{place.id==='hall'?'进入展示馆':place.id==='tea'||place.id==='workshop'?'与伙伴交流':'了解更多'}<ArrowUpRight size={17}/></button>}<button className="secondary-button" onClick={()=>{setPanel(null);apiRef.current?.focus(place.id);notice(`正在前往${place.short}`);}}><Footprints size={16}/>走过去</button></div></div></Dialog>}
  {panel==='chat'&&chatAgent&&<Dialog title={`与${chatAgent.name}聊聊`} subtitle={`${chatAgent.role} · AI 角色`} onClose={closeChat} className="chat-dialog" hidden={!!work}><div className="chat-mode"><span className="green-dot"/>{mode==='model'?'模型对话已连接':'本地资料演示 · 尚未连接语言模型'}</div><details className="public-memories"><summary>江湖见闻 · 公开活动记录</summary>{(agents.find(a=>a.id===chatId)?.memory||[]).length?(agents.find(a=>a.id===chatId)?.memory||[]).slice(-3).map((m,i)=><p key={i}>{m}</p>):<p>还没有与其他侠客交流的公开记录。</p>}</details><div className="chat-messages" ref={chatScroll} aria-live="polite">{(messages[chatId]||[]).map((m,i)=><div key={i} className={`message ${m.role} ${m.error?'error':''}`}>{m.role==='assistant'&&<Avatar agent={chatAgent} size={30}/>}<div className="message-body"><p>{m.content}</p>{m.workIds?.map(id=>{const w=allWorks.find(w=>w.id===id);return w?<button key={id} className="chat-work" onClick={()=>openWork(id)}><img src={w.thumb} alt=""/><span>{w.title}<small>{w.track}</small></span><ArrowUpRight size={15}/></button>:null;})}</div></div>)}{sending&&<div className="typing">{chatAgent.name}正在整理思绪<span>···</span></div>}</div><div className="quick-questions">{['推荐效率工具作品','介绍原子公社','你还记得我吗？'].map(q=><button key={q} disabled={sending} onClick={()=>sendMessage(q)}>{q}</button>)}</div><form className="chat-form" onSubmit={e=>{e.preventDefault();sendMessage();}}><input aria-label="聊天消息" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="聊聊你的想法…" maxLength={1000}/><button aria-label="发送消息" disabled={sending||!draft.trim()}><Send size={19}/></button></form><label className="memory-consent"><input type="checkbox" checked={remember} onChange={e=>changeRemember(e.target.checked)}/>记住我主动表达的兴趣，仅保存在此浏览器</label></Dialog>}
  {panel==='people'&&<Dialog title="同行侠客" subtitle="每个相逢，都可能是共创的开始" onClose={closePanel} className="people-dialog"><div className="people-list">{AGENTS.map(a=><button key={a.id} onClick={()=>startChat(a.id)}><Avatar agent={a} size={52}/><span><strong>{a.name}<i>AI</i></strong><p>{a.role}</p><small>{agents.find(x=>x.id===a.id)?.state}</small></span><MessageCircle size={20}/></button>)}</div><p className="source-note">角色为虚构 AI 伙伴，不代表真实主理人或作者。当前世界运行在本地浏览器。</p></Dialog>}
  {panel==='journal'&&<Dialog title="游历手札" subtitle="你的相逢与发现，留在这里" onClose={closePanel} className="journal-dialog" hidden={!!work}><div className="journal-tabs">{['收藏作品','最近看过','私人记忆'].map(t=><button className={journalTab===t?'active':''} key={t} onClick={()=>setJournalTab(t)}>{t}</button>)}</div>{journalTab==='私人记忆'?<div className="memory-list"><p>只有对应侠客会在你开启记忆时使用这些记录。删除会同步清除当前对话上下文。</p>{memories.length===0?<div className="empty-state"><Sparkles/><h3>还没有保存的记忆</h3><p>与侠客聊天时，你可以主动开启兴趣记忆。</p></div>:<>{memories.map(m=><article key={m.id}><Avatar agent={AGENTS.find(a=>a.id===m.agentId)}/><div><small>{AGENTS.find(a=>a.id===m.agentId)?.name} · {m.source}</small><p>{m.text}</p></div><button aria-label="删除这条记忆" className="icon-button" onClick={()=>deleteMemory(m.id)}><Trash2 size={16}/></button></article>)}<button className="danger-button" onClick={()=>deleteMemory()}>删除全部私人记忆</button></>}</div>:<div className="work-grid">{(journalTab==='收藏作品'?bookmarks:visits.map(v=>v.id)).map(id=>allWorks.find(w=>w.id===id)).filter(Boolean).map(workCard)}{(journalTab==='收藏作品'?bookmarks:visits).length===0&&<div className="empty-state"><BookOpen/><h3>手札的第一页，等你来写</h3><p>去展馆发现一个喜欢的作品吧。</p><button className="primary-button" onClick={enterHall}>去看看作品<ArrowRight size={16}/></button></div>}</div>}<p className="source-note">记录仅保存在此浏览器，尚未同步至账号。</p></Dialog>}
  {panel==='settings'&&<Dialog title="定制这片江湖" subtitle="你的侠客，你的小世界" onClose={closePanel} className="settings-dialog"><div className="settings-content"><h3>侠客名帖</h3><div className="profile-editor"><Avatar size={64} agent={{color:playerColor}}/><label>我的昵称<input value={nickname} onChange={e=>setNickname(e.target.value.slice(0,20))} maxLength={20} aria-label="我的昵称"/></label></div><label>衣带颜色</label><div className="color-options">{['#427ab5','#719783','#a17b9e','#b68b54','#be7770'].map(c=><button key={c} aria-label={`衣带颜色 ${c}`} className={c===playerColor?'active':''} style={{background:c}} onClick={()=>setPlayerColor(c)}>{c===playerColor&&<Check size={18}/>}</button>)}</div><h3>世界主题</h3><p className="setting-description">切换建筑与环境配色，保留原子公社的场景布局和真实作品。</p><div className="theme-options">{Object.entries(THEMES).map(([id,t])=><button key={id} className={id===theme?'active':''} onClick={()=>setTheme(id)}><span style={{background:t.roof}}/>{t.name}{theme===id&&<Check size={15}/>}</button>)}</div><label className="setting-toggle"><span>地图建筑标签</span><input type="checkbox" checked={showLabels} onChange={e=>setShowLabels(e.target.checked)}/></label><label className="setting-toggle"><span>灯火夜景</span><input type="checkbox" checked={night} onChange={e=>setNight(e.target.checked)}/></label><button className="secondary-button" onClick={()=>{setTheme('jianghu');setPlayerColor('#427ab5');setNight(false);setShowLabels(true);apiRef.current?.reset();}}>恢复默认场景</button></div></Dialog>}
  {panel==='about'&&<Dialog title="聚是一团火，散作满天星" subtitle="原子公社 ATOMHUB · 品牌与共建" onClose={closePanel} className="about-dialog"><div className="about-content"><img src="/brand/hero-ip.webp" alt="原子公社侠客 IP"/><div><span className="eyebrow">人与 AGENT 共建的开源学习社区</span><img className="original-logo" src="/brand/atomhub-logo.png" alt="原子公社 AtomHub 官方 Logo"/><h3>每个人都是一颗原子。</h3><p>人在这里提供经验与认知，Agent 带来效率与协助。一起分享真实案例、探索 AI 工具，把新的想法做成能解决问题的作品。</p><div className="values">{['个体至上','开放共享','务实求真','互助共赢','持续进化'].map((v,i)=><span key={v}><small>0{i+1}</small>{v}</span>)}</div><p>主理人是社区的“点灯人”。小镇将这份迎新与连接的职责交给阿原，将开放学习、共创实践和成果展示分别放进书院、工坊与比赛展示馆。</p><p className="source-note">品牌依据：《原子公社对外介绍 v2.2》 第 1、5—10、21 页。IP 来自你提供的素材。此版本为本地 3D 原型；真人联机、云端记忆及运营发布后台尚未接入。</p><a href="https://github.com/a16z-infra/ai-town" target="_blank" rel="noreferrer" className="text-button">技术参考 · AI Town<ExternalLink size={14}/></a></div></div></Dialog>}
 </div>;
}
